# Setup
title:        gen√©tica | enero 2021 | Ikiam
tagline:       
baseurl:      
url:          https://pesalerno.github.io/genetica-ago-2020/
paginate:     1
theme: jekyll-theme-cayman
future: true

# About/contact
author:
 name:       Patricia Salerno
 url:        https://patriciasalerno.wixsite.com/tepui

# Gems
plugins:
  - jekyll-paginate
  
# Google services
google_analytics: UA-144489144-1

#Others
site:
 

